[/]
audible-bell=false
cursor-blink-mode='system'
cursor-shape='ibeam'
default-columns=uint32 80
default-profile-uuid='3d1a5d0f4dc16c535512cd7368c8507b'
font-name='JetBrainsMono Nerd Font Mono 11'
interface-style='dark'
profile-uuids=['3d1a5d0f4dc16c535512cd7368c8507b']
restore-session=true
restore-window-size=false
scrollbar-policy='never'
text-blink-mode='always'
use-system-font=false
window-size=(uint32 212, uint32 51)

[Profiles/3d1a5d0f4dc16c535512cd7368c8507b]
bold-is-bright=false
cell-height-scale=1.0
palette='Catppuccin Mocha'