[tools]
ansible = { version = "latest", pipx_args = "--include-deps", uvx = false }
atuin = "latest"
herdr = "latest"
pipx = "latest"
trivy = "latest"
uv = "latest"
"npm:neovim" = "latest"

[settings.ruby]
compile = false